// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: annotation.proto
package com.codex.modelsheet.model;
public final class AnnotationOuterClass {
  private AnnotationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(AnnotationOuterClass.Annotation.compulsory);
    registry.add(AnnotationOuterClass.Annotation.allowedValuesKey);
    registry.add(AnnotationOuterClass.Annotation.unique);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnnotationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Annotation)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * This message contains annotations on general proto fields which can be used
   * for validation.
   * </pre>
   *
   * Protobuf type {@code Annotation}
   */
  public static final class Annotation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Annotation)
      AnnotationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Annotation.newBuilder() to construct.
    private Annotation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Annotation() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Annotation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Annotation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AnnotationOuterClass.internal_static_Annotation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AnnotationOuterClass.internal_static_Annotation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AnnotationOuterClass.Annotation.class, AnnotationOuterClass.Annotation.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AnnotationOuterClass.Annotation)) {
        return super.equals(obj);
      }
      AnnotationOuterClass.Annotation other = (AnnotationOuterClass.Annotation) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AnnotationOuterClass.Annotation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnnotationOuterClass.Annotation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnnotationOuterClass.Annotation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnnotationOuterClass.Annotation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnnotationOuterClass.Annotation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AnnotationOuterClass.Annotation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AnnotationOuterClass.Annotation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnnotationOuterClass.Annotation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnnotationOuterClass.Annotation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AnnotationOuterClass.Annotation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AnnotationOuterClass.Annotation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AnnotationOuterClass.Annotation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AnnotationOuterClass.Annotation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This message contains annotations on general proto fields which can be used
     * for validation.
     * </pre>
     *
     * Protobuf type {@code Annotation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Annotation)
        AnnotationOuterClass.AnnotationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AnnotationOuterClass.internal_static_Annotation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AnnotationOuterClass.internal_static_Annotation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AnnotationOuterClass.Annotation.class, AnnotationOuterClass.Annotation.Builder.class);
      }

      // Construct using AnnotationOuterClass.Annotation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AnnotationOuterClass.internal_static_Annotation_descriptor;
      }

      @java.lang.Override
      public AnnotationOuterClass.Annotation getDefaultInstanceForType() {
        return AnnotationOuterClass.Annotation.getDefaultInstance();
      }

      @java.lang.Override
      public AnnotationOuterClass.Annotation build() {
        AnnotationOuterClass.Annotation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AnnotationOuterClass.Annotation buildPartial() {
        AnnotationOuterClass.Annotation result = new AnnotationOuterClass.Annotation(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AnnotationOuterClass.Annotation) {
          return mergeFrom((AnnotationOuterClass.Annotation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AnnotationOuterClass.Annotation other) {
        if (other == AnnotationOuterClass.Annotation.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AnnotationOuterClass.Annotation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AnnotationOuterClass.Annotation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Annotation)
    }

    // @@protoc_insertion_point(class_scope:Annotation)
    private static final AnnotationOuterClass.Annotation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AnnotationOuterClass.Annotation();
    }

    public static AnnotationOuterClass.Annotation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Annotation>
        PARSER = new com.google.protobuf.AbstractParser<Annotation>() {
      @java.lang.Override
      public Annotation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Annotation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Annotation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Annotation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AnnotationOuterClass.Annotation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int COMPULSORY_FIELD_NUMBER = 70001;
    /**
     * <pre>
     * To validate fields which must be populated.
     * Usage:
     *  optional string id = 1 [(ValidationProperties.compulsory) = true];
     * </pre>
     *
     * <code>extend .google.protobuf.FieldOptions { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.protobuf.DescriptorProtos.FieldOptions,
        java.lang.Boolean> compulsory = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          AnnotationOuterClass.Annotation.getDefaultInstance(),
          0,
          java.lang.Boolean.class,
          null);
    public static final int ALLOWED_VALUES_KEY_FIELD_NUMBER = 70002;
    /**
     * <pre>
     * To validate fields that can only take values from a set of allowed
     * values.
     * Usage:
     *  optional string type = 1 [(ValidationProperties.allowed_values_key) = "chart_type"];
     *  Here, chart_type refers to a key in the allowed_values store.
     *  Refer to
     *  "java/common/src/main/java/com/thoughtspot/common/ProtoValidationBundle.java"
     *  for the role of allowed_values store and
     *  "common/allowed_values_store.proto" to understand how to populate it.
     * The allowed values store is defined in java/common/src/main/resources/allowed_values_store.pb
     * The allowed values store is a key value map, where the key is used in the annotation, and the
     * values are used as a set of allowed values for fields annotated with that key.
     * NOTE: The comparison with allowed values is CASE INSENSITIVE.
     * </pre>
     *
     * <code>extend .google.protobuf.FieldOptions { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.protobuf.DescriptorProtos.FieldOptions,
        java.lang.String> allowedValuesKey = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          AnnotationOuterClass.Annotation.getDefaultInstance(),
          1,
          java.lang.String.class,
          null);
    public static final int UNIQUE_FIELD_NUMBER = 70003;
    /**
     * <pre>
     * To validate that fields take unique values within a message when reached
     * through different paths. The property must be defined at the "root" of
     * the subtree, and the value should be a comma separated list of fields
     * in the subtree that should take unique values.
     * Usage:
     * message B {
     *   optional string b_1 = 1;
     * }
     * message A {
     *   repeated B a_1 = 1 [(Annotation.unique) = "b_1"];
     *   repeated B a_2 = 2 [(Annotation.unique) = "b_1"];
     * Example:
     *    {
     *        a_1 {
     *            b_1: "value_1"
     *        }
     *        a_1 {
     *            b_1: "value_1" // not allowed.
     *        }
     *        a_2 {
     *            b_1: "value_1" // allowed.
     *        }
     *        a_2 {
     *            b_1: "value_2" // allowed.
     *        }
     *    }
     * }
     * In this example, a_1.b_1 takes "value_1" twice. According to the
     * annotations in the proto, this is not allowed. a_2.b_1 takes distinct
     * values, which is allowed. "value_1" occurs in a_1.b_1 and a_2.b_1 and
     * this is allowed, because we only check for uniqueness in the subtree
     * formed with the root as the field which has the unique annotation.
     * NOTE: It is also allowed to specify deeper nested fields for unqie value validation.
     * For example:
     * message B {
     *   repeated C b_1 = 1;
     * }
     * message C {
     *   optional string c_1 = 1;
     * }
     * message A {
     *   optional B a_1 = 1 [(Annotation.unqiue) = "b_1.c_1"];
     * }
     * </pre>
     *
     * <code>extend .google.protobuf.FieldOptions { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        com.google.protobuf.DescriptorProtos.FieldOptions,
        java.lang.String> unique = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          AnnotationOuterClass.Annotation.getDefaultInstance(),
          2,
          java.lang.String.class,
          null);
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Annotation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Annotation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020annotation.proto\032 google/protobuf/desc" +
      "riptor.proto\"\257\001\n\nAnnotation23\n\ncompulsor" +
      "y\022\035.google.protobuf.FieldOptions\030\361\242\004 \001(\010" +
      "2;\n\022allowed_values_key\022\035.google.protobuf" +
      ".FieldOptions\030\362\242\004 \001(\t2/\n\006unique\022\035.google" +
      ".protobuf.FieldOptions\030\363\242\004 \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_Annotation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Annotation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Annotation_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
