// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cardinality_estimator.proto
package com.codex.modelsheet.importmodel;
public final class CardinalityEstimator {
  private CardinalityEstimator() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CardinalityEstimatorProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CardinalityEstimatorProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * This stores the ordered trailing maximum zeroes of each bucket which
     * can be used to calculate the estimated cardinality of the set.
     * These are also useful when the set is sharded and we want to
     * calculate the cardinality of the overall set by combining cardinality
     * estimate of each sharded subset. This can be done iff the number of
     * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
     * In this case, each ith value of each sharded subset correspond to the
     * same bucket.
     * </pre>
     *
     * <code>repeated int32 max_trailing_zeroes = 1;</code>
     * @return A list containing the maxTrailingZeroes.
     */
    java.util.List<java.lang.Integer> getMaxTrailingZeroesList();
    /**
     * <pre>
     * This stores the ordered trailing maximum zeroes of each bucket which
     * can be used to calculate the estimated cardinality of the set.
     * These are also useful when the set is sharded and we want to
     * calculate the cardinality of the overall set by combining cardinality
     * estimate of each sharded subset. This can be done iff the number of
     * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
     * In this case, each ith value of each sharded subset correspond to the
     * same bucket.
     * </pre>
     *
     * <code>repeated int32 max_trailing_zeroes = 1;</code>
     * @return The count of maxTrailingZeroes.
     */
    int getMaxTrailingZeroesCount();
    /**
     * <pre>
     * This stores the ordered trailing maximum zeroes of each bucket which
     * can be used to calculate the estimated cardinality of the set.
     * These are also useful when the set is sharded and we want to
     * calculate the cardinality of the overall set by combining cardinality
     * estimate of each sharded subset. This can be done iff the number of
     * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
     * In this case, each ith value of each sharded subset correspond to the
     * same bucket.
     * </pre>
     *
     * <code>repeated int32 max_trailing_zeroes = 1;</code>
     * @param index The index of the element to return.
     * @return The maxTrailingZeroes at the given index.
     */
    int getMaxTrailingZeroes(int index);
  }
  /**
   * <pre>
   * This message holds the cardinality estimator details for a set.
   * </pre>
   *
   * Protobuf type {@code CardinalityEstimatorProto}
   */
  public static final class CardinalityEstimatorProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CardinalityEstimatorProto)
      CardinalityEstimatorProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CardinalityEstimatorProto.newBuilder() to construct.
    private CardinalityEstimatorProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CardinalityEstimatorProto() {
      maxTrailingZeroes_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CardinalityEstimatorProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CardinalityEstimatorProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                maxTrailingZeroes_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              maxTrailingZeroes_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                maxTrailingZeroes_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                maxTrailingZeroes_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          maxTrailingZeroes_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CardinalityEstimator.internal_static_CardinalityEstimatorProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CardinalityEstimator.internal_static_CardinalityEstimatorProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CardinalityEstimator.CardinalityEstimatorProto.class, CardinalityEstimator.CardinalityEstimatorProto.Builder.class);
    }

    public static final int MAX_TRAILING_ZEROES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList maxTrailingZeroes_;
    /**
     * <pre>
     * This stores the ordered trailing maximum zeroes of each bucket which
     * can be used to calculate the estimated cardinality of the set.
     * These are also useful when the set is sharded and we want to
     * calculate the cardinality of the overall set by combining cardinality
     * estimate of each sharded subset. This can be done iff the number of
     * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
     * In this case, each ith value of each sharded subset correspond to the
     * same bucket.
     * </pre>
     *
     * <code>repeated int32 max_trailing_zeroes = 1;</code>
     * @return A list containing the maxTrailingZeroes.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getMaxTrailingZeroesList() {
      return maxTrailingZeroes_;
    }
    /**
     * <pre>
     * This stores the ordered trailing maximum zeroes of each bucket which
     * can be used to calculate the estimated cardinality of the set.
     * These are also useful when the set is sharded and we want to
     * calculate the cardinality of the overall set by combining cardinality
     * estimate of each sharded subset. This can be done iff the number of
     * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
     * In this case, each ith value of each sharded subset correspond to the
     * same bucket.
     * </pre>
     *
     * <code>repeated int32 max_trailing_zeroes = 1;</code>
     * @return The count of maxTrailingZeroes.
     */
    public int getMaxTrailingZeroesCount() {
      return maxTrailingZeroes_.size();
    }
    /**
     * <pre>
     * This stores the ordered trailing maximum zeroes of each bucket which
     * can be used to calculate the estimated cardinality of the set.
     * These are also useful when the set is sharded and we want to
     * calculate the cardinality of the overall set by combining cardinality
     * estimate of each sharded subset. This can be done iff the number of
     * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
     * In this case, each ith value of each sharded subset correspond to the
     * same bucket.
     * </pre>
     *
     * <code>repeated int32 max_trailing_zeroes = 1;</code>
     * @param index The index of the element to return.
     * @return The maxTrailingZeroes at the given index.
     */
    public int getMaxTrailingZeroes(int index) {
      return maxTrailingZeroes_.getInt(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < maxTrailingZeroes_.size(); i++) {
        output.writeInt32(1, maxTrailingZeroes_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < maxTrailingZeroes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(maxTrailingZeroes_.getInt(i));
        }
        size += dataSize;
        size += 1 * getMaxTrailingZeroesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CardinalityEstimator.CardinalityEstimatorProto)) {
        return super.equals(obj);
      }
      CardinalityEstimator.CardinalityEstimatorProto other = (CardinalityEstimator.CardinalityEstimatorProto) obj;

      if (!getMaxTrailingZeroesList()
          .equals(other.getMaxTrailingZeroesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMaxTrailingZeroesCount() > 0) {
        hash = (37 * hash) + MAX_TRAILING_ZEROES_FIELD_NUMBER;
        hash = (53 * hash) + getMaxTrailingZeroesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CardinalityEstimator.CardinalityEstimatorProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CardinalityEstimator.CardinalityEstimatorProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This message holds the cardinality estimator details for a set.
     * </pre>
     *
     * Protobuf type {@code CardinalityEstimatorProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CardinalityEstimatorProto)
        CardinalityEstimator.CardinalityEstimatorProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CardinalityEstimator.internal_static_CardinalityEstimatorProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CardinalityEstimator.internal_static_CardinalityEstimatorProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CardinalityEstimator.CardinalityEstimatorProto.class, CardinalityEstimator.CardinalityEstimatorProto.Builder.class);
      }

      // Construct using CardinalityEstimator.CardinalityEstimatorProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        maxTrailingZeroes_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CardinalityEstimator.internal_static_CardinalityEstimatorProto_descriptor;
      }

      @java.lang.Override
      public CardinalityEstimator.CardinalityEstimatorProto getDefaultInstanceForType() {
        return CardinalityEstimator.CardinalityEstimatorProto.getDefaultInstance();
      }

      @java.lang.Override
      public CardinalityEstimator.CardinalityEstimatorProto build() {
        CardinalityEstimator.CardinalityEstimatorProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CardinalityEstimator.CardinalityEstimatorProto buildPartial() {
        CardinalityEstimator.CardinalityEstimatorProto result = new CardinalityEstimator.CardinalityEstimatorProto(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          maxTrailingZeroes_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.maxTrailingZeroes_ = maxTrailingZeroes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CardinalityEstimator.CardinalityEstimatorProto) {
          return mergeFrom((CardinalityEstimator.CardinalityEstimatorProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CardinalityEstimator.CardinalityEstimatorProto other) {
        if (other == CardinalityEstimator.CardinalityEstimatorProto.getDefaultInstance()) return this;
        if (!other.maxTrailingZeroes_.isEmpty()) {
          if (maxTrailingZeroes_.isEmpty()) {
            maxTrailingZeroes_ = other.maxTrailingZeroes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMaxTrailingZeroesIsMutable();
            maxTrailingZeroes_.addAll(other.maxTrailingZeroes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CardinalityEstimator.CardinalityEstimatorProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CardinalityEstimator.CardinalityEstimatorProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList maxTrailingZeroes_ = emptyIntList();
      private void ensureMaxTrailingZeroesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          maxTrailingZeroes_ = mutableCopy(maxTrailingZeroes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * This stores the ordered trailing maximum zeroes of each bucket which
       * can be used to calculate the estimated cardinality of the set.
       * These are also useful when the set is sharded and we want to
       * calculate the cardinality of the overall set by combining cardinality
       * estimate of each sharded subset. This can be done iff the number of
       * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
       * In this case, each ith value of each sharded subset correspond to the
       * same bucket.
       * </pre>
       *
       * <code>repeated int32 max_trailing_zeroes = 1;</code>
       * @return A list containing the maxTrailingZeroes.
       */
      public java.util.List<java.lang.Integer>
          getMaxTrailingZeroesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(maxTrailingZeroes_) : maxTrailingZeroes_;
      }
      /**
       * <pre>
       * This stores the ordered trailing maximum zeroes of each bucket which
       * can be used to calculate the estimated cardinality of the set.
       * These are also useful when the set is sharded and we want to
       * calculate the cardinality of the overall set by combining cardinality
       * estimate of each sharded subset. This can be done iff the number of
       * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
       * In this case, each ith value of each sharded subset correspond to the
       * same bucket.
       * </pre>
       *
       * <code>repeated int32 max_trailing_zeroes = 1;</code>
       * @return The count of maxTrailingZeroes.
       */
      public int getMaxTrailingZeroesCount() {
        return maxTrailingZeroes_.size();
      }
      /**
       * <pre>
       * This stores the ordered trailing maximum zeroes of each bucket which
       * can be used to calculate the estimated cardinality of the set.
       * These are also useful when the set is sharded and we want to
       * calculate the cardinality of the overall set by combining cardinality
       * estimate of each sharded subset. This can be done iff the number of
       * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
       * In this case, each ith value of each sharded subset correspond to the
       * same bucket.
       * </pre>
       *
       * <code>repeated int32 max_trailing_zeroes = 1;</code>
       * @param index The index of the element to return.
       * @return The maxTrailingZeroes at the given index.
       */
      public int getMaxTrailingZeroes(int index) {
        return maxTrailingZeroes_.getInt(index);
      }
      /**
       * <pre>
       * This stores the ordered trailing maximum zeroes of each bucket which
       * can be used to calculate the estimated cardinality of the set.
       * These are also useful when the set is sharded and we want to
       * calculate the cardinality of the overall set by combining cardinality
       * estimate of each sharded subset. This can be done iff the number of
       * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
       * In this case, each ith value of each sharded subset correspond to the
       * same bucket.
       * </pre>
       *
       * <code>repeated int32 max_trailing_zeroes = 1;</code>
       * @param index The index to set the value at.
       * @param value The maxTrailingZeroes to set.
       * @return This builder for chaining.
       */
      public Builder setMaxTrailingZeroes(
          int index, int value) {
        ensureMaxTrailingZeroesIsMutable();
        maxTrailingZeroes_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This stores the ordered trailing maximum zeroes of each bucket which
       * can be used to calculate the estimated cardinality of the set.
       * These are also useful when the set is sharded and we want to
       * calculate the cardinality of the overall set by combining cardinality
       * estimate of each sharded subset. This can be done iff the number of
       * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
       * In this case, each ith value of each sharded subset correspond to the
       * same bucket.
       * </pre>
       *
       * <code>repeated int32 max_trailing_zeroes = 1;</code>
       * @param value The maxTrailingZeroes to add.
       * @return This builder for chaining.
       */
      public Builder addMaxTrailingZeroes(int value) {
        ensureMaxTrailingZeroesIsMutable();
        maxTrailingZeroes_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This stores the ordered trailing maximum zeroes of each bucket which
       * can be used to calculate the estimated cardinality of the set.
       * These are also useful when the set is sharded and we want to
       * calculate the cardinality of the overall set by combining cardinality
       * estimate of each sharded subset. This can be done iff the number of
       * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
       * In this case, each ith value of each sharded subset correspond to the
       * same bucket.
       * </pre>
       *
       * <code>repeated int32 max_trailing_zeroes = 1;</code>
       * @param values The maxTrailingZeroes to add.
       * @return This builder for chaining.
       */
      public Builder addAllMaxTrailingZeroes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMaxTrailingZeroesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, maxTrailingZeroes_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * This stores the ordered trailing maximum zeroes of each bucket which
       * can be used to calculate the estimated cardinality of the set.
       * These are also useful when the set is sharded and we want to
       * calculate the cardinality of the overall set by combining cardinality
       * estimate of each sharded subset. This can be done iff the number of
       * buckets are same i.e. the lengths of &#64;max_trailing_zeroes are equal.
       * In this case, each ith value of each sharded subset correspond to the
       * same bucket.
       * </pre>
       *
       * <code>repeated int32 max_trailing_zeroes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxTrailingZeroes() {
        maxTrailingZeroes_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CardinalityEstimatorProto)
    }

    // @@protoc_insertion_point(class_scope:CardinalityEstimatorProto)
    private static final CardinalityEstimator.CardinalityEstimatorProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CardinalityEstimator.CardinalityEstimatorProto();
    }

    public static CardinalityEstimator.CardinalityEstimatorProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CardinalityEstimatorProto>
        PARSER = new com.google.protobuf.AbstractParser<CardinalityEstimatorProto>() {
      @java.lang.Override
      public CardinalityEstimatorProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CardinalityEstimatorProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CardinalityEstimatorProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CardinalityEstimatorProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CardinalityEstimator.CardinalityEstimatorProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CardinalityEstimatorProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CardinalityEstimatorProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033cardinality_estimator.proto\"8\n\031Cardina" +
      "lityEstimatorProto\022\033\n\023max_trailing_zeroe" +
      "s\030\001 \003(\005"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CardinalityEstimatorProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CardinalityEstimatorProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CardinalityEstimatorProto_descriptor,
        new java.lang.String[] { "MaxTrailingZeroes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
