// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_type.proto
package com.codex.modelsheet.importmodel;
public final class DataTypeOuterClass {
  private DataTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataType)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * TODO(deshwal): Reconcile these types with the list of Value types.
   * TODO(deshwal): Consider folding this into query.proto once storage.proto
   *                is no longer there.
   * </pre>
   *
   * Protobuf type {@code DataType}
   */
  public static final class DataType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataType)
      DataTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataType.newBuilder() to construct.
    private DataType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataType() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataType();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DataTypeOuterClass.internal_static_DataType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DataTypeOuterClass.internal_static_DataType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DataTypeOuterClass.DataType.class, DataTypeOuterClass.DataType.Builder.class);
    }

    /**
     * <pre>
     * TODO(shashank,abhishek): From user's side, VarChar and Char should be
     * two distinct types. Otherwise it adds a third piece of metadata
     * (type, size, var_or_fixed) to be kept which is not very pretty.
     * Add VarChar as a type. It is already added in the Java side.  Once
     * added, replace existing Java column type enum with this.
     * </pre>
     *
     * Protobuf enum {@code DataType.E}
     */
    public enum E
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>BOOL = 1;</code>
       */
      BOOL(1),
      /**
       * <code>CHAR = 2;</code>
       */
      CHAR(2),
      /**
       * <code>DATE = 3;</code>
       */
      DATE(3),
      /**
       * <code>INT32 = 4;</code>
       */
      INT32(4),
      /**
       * <code>INT64 = 5;</code>
       */
      INT64(5),
      /**
       * <code>FLOAT = 6;</code>
       */
      FLOAT(6),
      /**
       * <code>DOUBLE = 7;</code>
       */
      DOUBLE(7),
      /**
       * <code>DATE_TIME = 8;</code>
       */
      DATE_TIME(8),
      /**
       * <code>TIME = 9;</code>
       */
      TIME(9),
      ;

      /**
       * <code>MAX_TYPE = 9;</code>
       */
      public static final E MAX_TYPE = TIME;
      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>BOOL = 1;</code>
       */
      public static final int BOOL_VALUE = 1;
      /**
       * <code>CHAR = 2;</code>
       */
      public static final int CHAR_VALUE = 2;
      /**
       * <code>DATE = 3;</code>
       */
      public static final int DATE_VALUE = 3;
      /**
       * <code>INT32 = 4;</code>
       */
      public static final int INT32_VALUE = 4;
      /**
       * <code>INT64 = 5;</code>
       */
      public static final int INT64_VALUE = 5;
      /**
       * <code>FLOAT = 6;</code>
       */
      public static final int FLOAT_VALUE = 6;
      /**
       * <code>DOUBLE = 7;</code>
       */
      public static final int DOUBLE_VALUE = 7;
      /**
       * <code>DATE_TIME = 8;</code>
       */
      public static final int DATE_TIME_VALUE = 8;
      /**
       * <code>TIME = 9;</code>
       */
      public static final int TIME_VALUE = 9;
      /**
       * <code>MAX_TYPE = 9;</code>
       */
      public static final int MAX_TYPE_VALUE = 9;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return BOOL;
          case 2: return CHAR;
          case 3: return DATE;
          case 4: return INT32;
          case 5: return INT64;
          case 6: return FLOAT;
          case 7: return DOUBLE;
          case 8: return DATE_TIME;
          case 9: return TIME;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E>() {
              public E findValueByNumber(int number) {
                return E.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DataTypeOuterClass.DataType.getDescriptor().getEnumTypes().get(0);
      }

      private static final E[] VALUES = getStaticValuesArray();
      private static E[] getStaticValuesArray() {
        return new E[] {
          UNKNOWN, BOOL, CHAR, DATE, INT32, INT64, FLOAT, DOUBLE, DATE_TIME, TIME, MAX_TYPE, 
        };
      }
      public static E valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:DataType.E)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DataTypeOuterClass.DataType)) {
        return super.equals(obj);
      }
      DataTypeOuterClass.DataType other = (DataTypeOuterClass.DataType) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DataTypeOuterClass.DataType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataTypeOuterClass.DataType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataTypeOuterClass.DataType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataTypeOuterClass.DataType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataTypeOuterClass.DataType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DataTypeOuterClass.DataType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DataTypeOuterClass.DataType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataTypeOuterClass.DataType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataTypeOuterClass.DataType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DataTypeOuterClass.DataType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DataTypeOuterClass.DataType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DataTypeOuterClass.DataType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DataTypeOuterClass.DataType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * TODO(deshwal): Reconcile these types with the list of Value types.
     * TODO(deshwal): Consider folding this into query.proto once storage.proto
     *                is no longer there.
     * </pre>
     *
     * Protobuf type {@code DataType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataType)
        DataTypeOuterClass.DataTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DataTypeOuterClass.internal_static_DataType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DataTypeOuterClass.internal_static_DataType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DataTypeOuterClass.DataType.class, DataTypeOuterClass.DataType.Builder.class);
      }

      // Construct using DataTypeOuterClass.DataType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DataTypeOuterClass.internal_static_DataType_descriptor;
      }

      @java.lang.Override
      public DataTypeOuterClass.DataType getDefaultInstanceForType() {
        return DataTypeOuterClass.DataType.getDefaultInstance();
      }

      @java.lang.Override
      public DataTypeOuterClass.DataType build() {
        DataTypeOuterClass.DataType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DataTypeOuterClass.DataType buildPartial() {
        DataTypeOuterClass.DataType result = new DataTypeOuterClass.DataType(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DataTypeOuterClass.DataType) {
          return mergeFrom((DataTypeOuterClass.DataType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DataTypeOuterClass.DataType other) {
        if (other == DataTypeOuterClass.DataType.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DataTypeOuterClass.DataType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DataTypeOuterClass.DataType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataType)
    }

    // @@protoc_insertion_point(class_scope:DataType)
    private static final DataTypeOuterClass.DataType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DataTypeOuterClass.DataType();
    }

    public static DataTypeOuterClass.DataType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DataType>
        PARSER = new com.google.protobuf.AbstractParser<DataType>() {
      @java.lang.Override
      public DataType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DataTypeOuterClass.DataType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017data_type.proto\"\223\001\n\010DataType\"\206\001\n\001E\022\013\n\007" +
      "UNKNOWN\020\000\022\010\n\004BOOL\020\001\022\010\n\004CHAR\020\002\022\010\n\004DATE\020\003\022" +
      "\t\n\005INT32\020\004\022\t\n\005INT64\020\005\022\t\n\005FLOAT\020\006\022\n\n\006DOUB" +
      "LE\020\007\022\r\n\tDATE_TIME\020\010\022\010\n\004TIME\020\t\022\014\n\010MAX_TYP" +
      "E\020\t\032\002\020\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DataType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataType_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
