// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edoc_common.proto
package com.codex.modelsheet.importmodel;
public final class EdocCommon {
  private EdocCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EDocFormatTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EDocFormatType)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * Format type of the TML file.
   * </pre>
   *
   * Protobuf type {@code EDocFormatType}
   */
  public static final class EDocFormatType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EDocFormatType)
      EDocFormatTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EDocFormatType.newBuilder() to construct.
    private EDocFormatType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EDocFormatType() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EDocFormatType();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EDocFormatType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EdocCommon.internal_static_EDocFormatType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EdocCommon.internal_static_EDocFormatType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EdocCommon.EDocFormatType.class, EdocCommon.EDocFormatType.Builder.class);
    }

    /**
     * Protobuf enum {@code EDocFormatType.E}
     */
    public enum E
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>YAML = 1;</code>
       */
      YAML(1),
      /**
       * <code>JSON = 2;</code>
       */
      JSON(2),
      /**
       * <code>PROTO = 3;</code>
       */
      PROTO(3),
      ;

      /**
       * <code>YAML = 1;</code>
       */
      public static final int YAML_VALUE = 1;
      /**
       * <code>JSON = 2;</code>
       */
      public static final int JSON_VALUE = 2;
      /**
       * <code>PROTO = 3;</code>
       */
      public static final int PROTO_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E forNumber(int value) {
        switch (value) {
          case 1: return YAML;
          case 2: return JSON;
          case 3: return PROTO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E>() {
              public E findValueByNumber(int number) {
                return E.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return EdocCommon.EDocFormatType.getDescriptor().getEnumTypes().get(0);
      }

      private static final E[] VALUES = values();

      public static E valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:EDocFormatType.E)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EdocCommon.EDocFormatType)) {
        return super.equals(obj);
      }
      EdocCommon.EDocFormatType other = (EdocCommon.EDocFormatType) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EdocCommon.EDocFormatType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.EDocFormatType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.EDocFormatType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.EDocFormatType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.EDocFormatType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.EDocFormatType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.EDocFormatType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EdocCommon.EDocFormatType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EdocCommon.EDocFormatType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EdocCommon.EDocFormatType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EdocCommon.EDocFormatType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EdocCommon.EDocFormatType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EdocCommon.EDocFormatType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Format type of the TML file.
     * </pre>
     *
     * Protobuf type {@code EDocFormatType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EDocFormatType)
        EdocCommon.EDocFormatTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EdocCommon.internal_static_EDocFormatType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EdocCommon.internal_static_EDocFormatType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EdocCommon.EDocFormatType.class, EdocCommon.EDocFormatType.Builder.class);
      }

      // Construct using EdocCommon.EDocFormatType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EdocCommon.internal_static_EDocFormatType_descriptor;
      }

      @java.lang.Override
      public EdocCommon.EDocFormatType getDefaultInstanceForType() {
        return EdocCommon.EDocFormatType.getDefaultInstance();
      }

      @java.lang.Override
      public EdocCommon.EDocFormatType build() {
        EdocCommon.EDocFormatType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EdocCommon.EDocFormatType buildPartial() {
        EdocCommon.EDocFormatType result = new EdocCommon.EDocFormatType(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EdocCommon.EDocFormatType) {
          return mergeFrom((EdocCommon.EDocFormatType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EdocCommon.EDocFormatType other) {
        if (other == EdocCommon.EDocFormatType.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EdocCommon.EDocFormatType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EdocCommon.EDocFormatType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EDocFormatType)
    }

    // @@protoc_insertion_point(class_scope:EDocFormatType)
    private static final EdocCommon.EDocFormatType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EdocCommon.EDocFormatType();
    }

    public static EdocCommon.EDocFormatType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EDocFormatType>
        PARSER = new com.google.protobuf.AbstractParser<EDocFormatType>() {
      @java.lang.Override
      public EDocFormatType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EDocFormatType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EDocFormatType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EDocFormatType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EdocCommon.EDocFormatType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EDocObjectTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EDocObjectType)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * Type of exportable objects.
   * </pre>
   *
   * Protobuf type {@code EDocObjectType}
   */
  public static final class EDocObjectType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EDocObjectType)
      EDocObjectTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EDocObjectType.newBuilder() to construct.
    private EDocObjectType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EDocObjectType() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EDocObjectType();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EDocObjectType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EdocCommon.internal_static_EDocObjectType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EdocCommon.internal_static_EDocObjectType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EdocCommon.EDocObjectType.class, EdocCommon.EDocObjectType.Builder.class);
    }

    /**
     * Protobuf enum {@code EDocObjectType.E}
     */
    public enum E
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ANSWER = 0;</code>
       */
      ANSWER(0),
      /**
       * <code>PINBOARD = 1;</code>
       */
      PINBOARD(1),
      /**
       * <code>WORKSHEET = 2;</code>
       */
      WORKSHEET(2),
      /**
       * <code>VIEW = 3;</code>
       */
      VIEW(3),
      /**
       * <code>TABLE = 4;</code>
       */
      TABLE(4),
      /**
       * <pre>
       * JOIN is a internal type. We don't have accept individual JOINs in edoc
       * but it is used internally.
       * </pre>
       *
       * <code>JOIN = 5;</code>
       */
      JOIN(5),
      /**
       * <pre>
       *-------------------------------------------------------------------------|
       * Following types are deprecated and their usage is strongly discouraged.//
       * They exists for backward compatibility while the usage of              //
       * 'MetadataTypeEnum' from edoc.                                          //
       * </pre>
       *
       * <code>LOGICAL_TABLE = 10000;</code>
       */
      LOGICAL_TABLE(10000),
      /**
       * <pre>
       * </pre>
       *
       * <code>PINBOARD_ANSWER_BOOK = 10001;</code>
       */
      PINBOARD_ANSWER_BOOK(10001),
      /**
       * <pre>
       * </pre>
       *
       * <code>QUESTION_ANSWER_BOOK = 10002;</code>
       */
      QUESTION_ANSWER_BOOK(10002),
      ;

      /**
       * <code>ANSWER = 0;</code>
       */
      public static final int ANSWER_VALUE = 0;
      /**
       * <code>PINBOARD = 1;</code>
       */
      public static final int PINBOARD_VALUE = 1;
      /**
       * <code>WORKSHEET = 2;</code>
       */
      public static final int WORKSHEET_VALUE = 2;
      /**
       * <code>VIEW = 3;</code>
       */
      public static final int VIEW_VALUE = 3;
      /**
       * <code>TABLE = 4;</code>
       */
      public static final int TABLE_VALUE = 4;
      /**
       * <pre>
       * JOIN is a internal type. We don't have accept individual JOINs in edoc
       * but it is used internally.
       * </pre>
       *
       * <code>JOIN = 5;</code>
       */
      public static final int JOIN_VALUE = 5;
      /**
       * <pre>
       *-------------------------------------------------------------------------|
       * Following types are deprecated and their usage is strongly discouraged.//
       * They exists for backward compatibility while the usage of              //
       * 'MetadataTypeEnum' from edoc.                                          //
       * </pre>
       *
       * <code>LOGICAL_TABLE = 10000;</code>
       */
      public static final int LOGICAL_TABLE_VALUE = 10000;
      /**
       * <pre>
       * </pre>
       *
       * <code>PINBOARD_ANSWER_BOOK = 10001;</code>
       */
      public static final int PINBOARD_ANSWER_BOOK_VALUE = 10001;
      /**
       * <pre>
       * </pre>
       *
       * <code>QUESTION_ANSWER_BOOK = 10002;</code>
       */
      public static final int QUESTION_ANSWER_BOOK_VALUE = 10002;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E forNumber(int value) {
        switch (value) {
          case 0: return ANSWER;
          case 1: return PINBOARD;
          case 2: return WORKSHEET;
          case 3: return VIEW;
          case 4: return TABLE;
          case 5: return JOIN;
          case 10000: return LOGICAL_TABLE;
          case 10001: return PINBOARD_ANSWER_BOOK;
          case 10002: return QUESTION_ANSWER_BOOK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E>() {
              public E findValueByNumber(int number) {
                return E.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return EdocCommon.EDocObjectType.getDescriptor().getEnumTypes().get(0);
      }

      private static final E[] VALUES = values();

      public static E valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:EDocObjectType.E)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EdocCommon.EDocObjectType)) {
        return super.equals(obj);
      }
      EdocCommon.EDocObjectType other = (EdocCommon.EDocObjectType) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EdocCommon.EDocObjectType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.EDocObjectType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.EDocObjectType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.EDocObjectType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.EDocObjectType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.EDocObjectType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.EDocObjectType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EdocCommon.EDocObjectType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EdocCommon.EDocObjectType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EdocCommon.EDocObjectType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EdocCommon.EDocObjectType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EdocCommon.EDocObjectType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EdocCommon.EDocObjectType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Type of exportable objects.
     * </pre>
     *
     * Protobuf type {@code EDocObjectType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EDocObjectType)
        EdocCommon.EDocObjectTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EdocCommon.internal_static_EDocObjectType_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EdocCommon.internal_static_EDocObjectType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EdocCommon.EDocObjectType.class, EdocCommon.EDocObjectType.Builder.class);
      }

      // Construct using EdocCommon.EDocObjectType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EdocCommon.internal_static_EDocObjectType_descriptor;
      }

      @java.lang.Override
      public EdocCommon.EDocObjectType getDefaultInstanceForType() {
        return EdocCommon.EDocObjectType.getDefaultInstance();
      }

      @java.lang.Override
      public EdocCommon.EDocObjectType build() {
        EdocCommon.EDocObjectType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EdocCommon.EDocObjectType buildPartial() {
        EdocCommon.EDocObjectType result = new EdocCommon.EDocObjectType(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EdocCommon.EDocObjectType) {
          return mergeFrom((EdocCommon.EDocObjectType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EdocCommon.EDocObjectType other) {
        if (other == EdocCommon.EDocObjectType.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EdocCommon.EDocObjectType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EdocCommon.EDocObjectType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EDocObjectType)
    }

    // @@protoc_insertion_point(class_scope:EDocObjectType)
    private static final EdocCommon.EDocObjectType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EdocCommon.EDocObjectType();
    }

    public static EdocCommon.EDocObjectType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EDocObjectType>
        PARSER = new com.google.protobuf.AbstractParser<EDocObjectType>() {
      @java.lang.Override
      public EDocObjectType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EDocObjectType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EDocObjectType> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EDocObjectType> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EdocCommon.EDocObjectType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ImportActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImportAction)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * Type of import action
   * - CREATE creates a new entity
   * - UPDATE updates an existing entity
   * </pre>
   *
   * Protobuf type {@code ImportAction}
   */
  public static final class ImportAction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImportAction)
      ImportActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImportAction.newBuilder() to construct.
    private ImportAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImportAction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImportAction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImportAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EdocCommon.internal_static_ImportAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EdocCommon.internal_static_ImportAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EdocCommon.ImportAction.class, EdocCommon.ImportAction.Builder.class);
    }

    /**
     * Protobuf enum {@code ImportAction.E}
     */
    public enum E
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CREATE = 1;</code>
       */
      CREATE(1),
      /**
       * <code>UPDATE = 2;</code>
       */
      UPDATE(2),
      /**
       * <code>UPDATE_OR_CREATE = 3;</code>
       */
      UPDATE_OR_CREATE(3),
      ;

      /**
       * <code>CREATE = 1;</code>
       */
      public static final int CREATE_VALUE = 1;
      /**
       * <code>UPDATE = 2;</code>
       */
      public static final int UPDATE_VALUE = 2;
      /**
       * <code>UPDATE_OR_CREATE = 3;</code>
       */
      public static final int UPDATE_OR_CREATE_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static E valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static E forNumber(int value) {
        switch (value) {
          case 1: return CREATE;
          case 2: return UPDATE;
          case 3: return UPDATE_OR_CREATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<E>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          E> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<E>() {
              public E findValueByNumber(int number) {
                return E.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return EdocCommon.ImportAction.getDescriptor().getEnumTypes().get(0);
      }

      private static final E[] VALUES = values();

      public static E valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private E(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImportAction.E)
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EdocCommon.ImportAction)) {
        return super.equals(obj);
      }
      EdocCommon.ImportAction other = (EdocCommon.ImportAction) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EdocCommon.ImportAction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.ImportAction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.ImportAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.ImportAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.ImportAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EdocCommon.ImportAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EdocCommon.ImportAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EdocCommon.ImportAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EdocCommon.ImportAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EdocCommon.ImportAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EdocCommon.ImportAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EdocCommon.ImportAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EdocCommon.ImportAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Type of import action
     * - CREATE creates a new entity
     * - UPDATE updates an existing entity
     * </pre>
     *
     * Protobuf type {@code ImportAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImportAction)
        EdocCommon.ImportActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EdocCommon.internal_static_ImportAction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EdocCommon.internal_static_ImportAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EdocCommon.ImportAction.class, EdocCommon.ImportAction.Builder.class);
      }

      // Construct using EdocCommon.ImportAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EdocCommon.internal_static_ImportAction_descriptor;
      }

      @java.lang.Override
      public EdocCommon.ImportAction getDefaultInstanceForType() {
        return EdocCommon.ImportAction.getDefaultInstance();
      }

      @java.lang.Override
      public EdocCommon.ImportAction build() {
        EdocCommon.ImportAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public EdocCommon.ImportAction buildPartial() {
        EdocCommon.ImportAction result = new EdocCommon.ImportAction(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EdocCommon.ImportAction) {
          return mergeFrom((EdocCommon.ImportAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EdocCommon.ImportAction other) {
        if (other == EdocCommon.ImportAction.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EdocCommon.ImportAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EdocCommon.ImportAction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImportAction)
    }

    // @@protoc_insertion_point(class_scope:ImportAction)
    private static final EdocCommon.ImportAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EdocCommon.ImportAction();
    }

    public static EdocCommon.ImportAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ImportAction>
        PARSER = new com.google.protobuf.AbstractParser<ImportAction>() {
      @java.lang.Override
      public ImportAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImportAction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImportAction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImportAction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public EdocCommon.ImportAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EDocFormatType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EDocFormatType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EDocObjectType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EDocObjectType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImportAction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImportAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021edoc_common.proto\"4\n\016EDocFormatType\"\"\n" +
      "\001E\022\010\n\004YAML\020\001\022\010\n\004JSON\020\002\022\t\n\005PROTO\020\003\"\250\001\n\016ED" +
      "ocObjectType\"\225\001\n\001E\022\n\n\006ANSWER\020\000\022\014\n\010PINBOA" +
      "RD\020\001\022\r\n\tWORKSHEET\020\002\022\010\n\004VIEW\020\003\022\t\n\005TABLE\020\004" +
      "\022\010\n\004JOIN\020\005\022\022\n\rLOGICAL_TABLE\020\220N\022\031\n\024PINBOA" +
      "RD_ANSWER_BOOK\020\221N\022\031\n\024QUESTION_ANSWER_BOO" +
      "K\020\222N\"A\n\014ImportAction\"1\n\001E\022\n\n\006CREATE\020\001\022\n\n" +
      "\006UPDATE\020\002\022\024\n\020UPDATE_OR_CREATE\020\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_EDocFormatType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EDocFormatType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EDocFormatType_descriptor,
        new java.lang.String[] { });
    internal_static_EDocObjectType_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EDocObjectType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EDocObjectType_descriptor,
        new java.lang.String[] { });
    internal_static_ImportAction_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ImportAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImportAction_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
