// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partition_window.proto
package com.codex.modelsheet.importmodel;
public final class PartitionWindowOuterClass {
  private PartitionWindowOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PartitionWindowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PartitionWindow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .PartitionWindow.Point start = 1;</code>
     * @return Whether the start field is set.
     */
    boolean hasStart();
    /**
     * <code>optional .PartitionWindow.Point start = 1;</code>
     * @return The start.
     */
    PartitionWindowOuterClass.PartitionWindow.Point getStart();
    /**
     * <code>optional .PartitionWindow.Point start = 1;</code>
     */
    PartitionWindowOuterClass.PartitionWindow.PointOrBuilder getStartOrBuilder();

    /**
     * <code>optional .PartitionWindow.Point end = 2;</code>
     * @return Whether the end field is set.
     */
    boolean hasEnd();
    /**
     * <code>optional .PartitionWindow.Point end = 2;</code>
     * @return The end.
     */
    PartitionWindowOuterClass.PartitionWindow.Point getEnd();
    /**
     * <code>optional .PartitionWindow.Point end = 2;</code>
     */
    PartitionWindowOuterClass.PartitionWindow.PointOrBuilder getEndOrBuilder();

    /**
     * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
     * @return Whether the windowType field is set.
     */
    boolean hasWindowType();
    /**
     * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
     * @return The windowType.
     */
    PartitionWindowOuterClass.PartitionWindow.WindowType getWindowType();
  }
  /**
   * Protobuf type {@code PartitionWindow}
   */
  public static final class PartitionWindow extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PartitionWindow)
      PartitionWindowOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PartitionWindow.newBuilder() to construct.
    private PartitionWindow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PartitionWindow() {
      windowType_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PartitionWindow();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PartitionWindow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              PartitionWindowOuterClass.PartitionWindow.Point.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) != 0)) {
                subBuilder = start_.toBuilder();
              }
              start_ = input.readMessage(PartitionWindowOuterClass.PartitionWindow.Point.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(start_);
                start_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              PartitionWindowOuterClass.PartitionWindow.Point.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = end_.toBuilder();
              }
              end_ = input.readMessage(PartitionWindowOuterClass.PartitionWindow.Point.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(end_);
                end_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              PartitionWindowOuterClass.PartitionWindow.WindowType value = PartitionWindowOuterClass.PartitionWindow.WindowType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                windowType_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PartitionWindowOuterClass.internal_static_PartitionWindow_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PartitionWindowOuterClass.internal_static_PartitionWindow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PartitionWindowOuterClass.PartitionWindow.class, PartitionWindowOuterClass.PartitionWindow.Builder.class);
    }

    /**
     * Protobuf enum {@code PartitionWindow.PointType}
     */
    public enum PointType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNBOUNDED_PRECEDING = 1;</code>
       */
      UNBOUNDED_PRECEDING(1),
      /**
       * <code>PRECEDING = 2;</code>
       */
      PRECEDING(2),
      /**
       * <code>UNBOUNDED_FOLLOWING = 3;</code>
       */
      UNBOUNDED_FOLLOWING(3),
      /**
       * <code>FOLLOWING = 4;</code>
       */
      FOLLOWING(4),
      /**
       * <code>CURRENT_ROW = 5;</code>
       */
      CURRENT_ROW(5),
      ;

      /**
       * <code>UNBOUNDED_PRECEDING = 1;</code>
       */
      public static final int UNBOUNDED_PRECEDING_VALUE = 1;
      /**
       * <code>PRECEDING = 2;</code>
       */
      public static final int PRECEDING_VALUE = 2;
      /**
       * <code>UNBOUNDED_FOLLOWING = 3;</code>
       */
      public static final int UNBOUNDED_FOLLOWING_VALUE = 3;
      /**
       * <code>FOLLOWING = 4;</code>
       */
      public static final int FOLLOWING_VALUE = 4;
      /**
       * <code>CURRENT_ROW = 5;</code>
       */
      public static final int CURRENT_ROW_VALUE = 5;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PointType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PointType forNumber(int value) {
        switch (value) {
          case 1: return UNBOUNDED_PRECEDING;
          case 2: return PRECEDING;
          case 3: return UNBOUNDED_FOLLOWING;
          case 4: return FOLLOWING;
          case 5: return CURRENT_ROW;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PointType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PointType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PointType>() {
              public PointType findValueByNumber(int number) {
                return PointType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PartitionWindowOuterClass.PartitionWindow.getDescriptor().getEnumTypes().get(0);
      }

      private static final PointType[] VALUES = values();

      public static PointType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PointType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PartitionWindow.PointType)
    }

    /**
     * Protobuf enum {@code PartitionWindow.WindowType}
     */
    public enum WindowType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RANGE = 1;</code>
       */
      RANGE(1),
      /**
       * <code>ROW = 2;</code>
       */
      ROW(2),
      ;

      /**
       * <code>RANGE = 1;</code>
       */
      public static final int RANGE_VALUE = 1;
      /**
       * <code>ROW = 2;</code>
       */
      public static final int ROW_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WindowType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static WindowType forNumber(int value) {
        switch (value) {
          case 1: return RANGE;
          case 2: return ROW;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<WindowType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          WindowType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WindowType>() {
              public WindowType findValueByNumber(int number) {
                return WindowType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PartitionWindowOuterClass.PartitionWindow.getDescriptor().getEnumTypes().get(1);
      }

      private static final WindowType[] VALUES = values();

      public static WindowType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private WindowType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PartitionWindow.WindowType)
    }

    public interface PointOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PartitionWindow.Point)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional .PartitionWindow.PointType type = 1;</code>
       * @return Whether the type field is set.
       */
      boolean hasType();
      /**
       * <code>optional .PartitionWindow.PointType type = 1;</code>
       * @return The type.
       */
      PartitionWindowOuterClass.PartitionWindow.PointType getType();

      /**
       * <pre>
       * Can be PRECEDING or FOLLOWING.
       * </pre>
       *
       * <code>optional sint64 n = 2;</code>
       * @return Whether the n field is set.
       */
      boolean hasN();
      /**
       * <pre>
       * Can be PRECEDING or FOLLOWING.
       * </pre>
       *
       * <code>optional sint64 n = 2;</code>
       * @return The n.
       */
      long getN();
    }
    /**
     * Protobuf type {@code PartitionWindow.Point}
     */
    public static final class Point extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:PartitionWindow.Point)
        PointOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Point.newBuilder() to construct.
      private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Point() {
        type_ = 1;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Point();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Point(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                PartitionWindowOuterClass.PartitionWindow.PointType value = PartitionWindowOuterClass.PartitionWindow.PointType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  type_ = rawValue;
                }
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                n_ = input.readSInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PartitionWindowOuterClass.internal_static_PartitionWindow_Point_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PartitionWindowOuterClass.internal_static_PartitionWindow_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PartitionWindowOuterClass.PartitionWindow.Point.class, PartitionWindowOuterClass.PartitionWindow.Point.Builder.class);
      }

      private int bitField0_;
      public static final int TYPE_FIELD_NUMBER = 1;
      private int type_;
      /**
       * <code>optional .PartitionWindow.PointType type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .PartitionWindow.PointType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override public PartitionWindowOuterClass.PartitionWindow.PointType getType() {
        @SuppressWarnings("deprecation")
        PartitionWindowOuterClass.PartitionWindow.PointType result = PartitionWindowOuterClass.PartitionWindow.PointType.valueOf(type_);
        return result == null ? PartitionWindowOuterClass.PartitionWindow.PointType.UNBOUNDED_PRECEDING : result;
      }

      public static final int N_FIELD_NUMBER = 2;
      private long n_;
      /**
       * <pre>
       * Can be PRECEDING or FOLLOWING.
       * </pre>
       *
       * <code>optional sint64 n = 2;</code>
       * @return Whether the n field is set.
       */
      @java.lang.Override
      public boolean hasN() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Can be PRECEDING or FOLLOWING.
       * </pre>
       *
       * <code>optional sint64 n = 2;</code>
       * @return The n.
       */
      @java.lang.Override
      public long getN() {
        return n_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeEnum(1, type_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeSInt64(2, n_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeSInt64Size(2, n_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof PartitionWindowOuterClass.PartitionWindow.Point)) {
          return super.equals(obj);
        }
        PartitionWindowOuterClass.PartitionWindow.Point other = (PartitionWindowOuterClass.PartitionWindow.Point) obj;

        if (hasType() != other.hasType()) return false;
        if (hasType()) {
          if (type_ != other.type_) return false;
        }
        if (hasN() != other.hasN()) return false;
        if (hasN()) {
          if (getN()
              != other.getN()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasType()) {
          hash = (37 * hash) + TYPE_FIELD_NUMBER;
          hash = (53 * hash) + type_;
        }
        if (hasN()) {
          hash = (37 * hash) + N_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getN());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static PartitionWindowOuterClass.PartitionWindow.Point parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(PartitionWindowOuterClass.PartitionWindow.Point prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PartitionWindow.Point}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PartitionWindow.Point)
          PartitionWindowOuterClass.PartitionWindow.PointOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PartitionWindowOuterClass.internal_static_PartitionWindow_Point_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PartitionWindowOuterClass.internal_static_PartitionWindow_Point_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PartitionWindowOuterClass.PartitionWindow.Point.class, PartitionWindowOuterClass.PartitionWindow.Point.Builder.class);
        }

        // Construct using PartitionWindowOuterClass.PartitionWindow.Point.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          type_ = 1;
          bitField0_ = (bitField0_ & ~0x00000001);
          n_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PartitionWindowOuterClass.internal_static_PartitionWindow_Point_descriptor;
        }

        @java.lang.Override
        public PartitionWindowOuterClass.PartitionWindow.Point getDefaultInstanceForType() {
          return PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance();
        }

        @java.lang.Override
        public PartitionWindowOuterClass.PartitionWindow.Point build() {
          PartitionWindowOuterClass.PartitionWindow.Point result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public PartitionWindowOuterClass.PartitionWindow.Point buildPartial() {
          PartitionWindowOuterClass.PartitionWindow.Point result = new PartitionWindowOuterClass.PartitionWindow.Point(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.n_ = n_;
            to_bitField0_ |= 0x00000002;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PartitionWindowOuterClass.PartitionWindow.Point) {
            return mergeFrom((PartitionWindowOuterClass.PartitionWindow.Point)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PartitionWindowOuterClass.PartitionWindow.Point other) {
          if (other == PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasN()) {
            setN(other.getN());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          PartitionWindowOuterClass.PartitionWindow.Point parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (PartitionWindowOuterClass.PartitionWindow.Point) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int type_ = 1;
        /**
         * <code>optional .PartitionWindow.PointType type = 1;</code>
         * @return Whether the type field is set.
         */
        @java.lang.Override public boolean hasType() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional .PartitionWindow.PointType type = 1;</code>
         * @return The type.
         */
        @java.lang.Override
        public PartitionWindowOuterClass.PartitionWindow.PointType getType() {
          @SuppressWarnings("deprecation")
          PartitionWindowOuterClass.PartitionWindow.PointType result = PartitionWindowOuterClass.PartitionWindow.PointType.valueOf(type_);
          return result == null ? PartitionWindowOuterClass.PartitionWindow.PointType.UNBOUNDED_PRECEDING : result;
        }
        /**
         * <code>optional .PartitionWindow.PointType type = 1;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(PartitionWindowOuterClass.PartitionWindow.PointType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .PartitionWindow.PointType type = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = 1;
          onChanged();
          return this;
        }

        private long n_ ;
        /**
         * <pre>
         * Can be PRECEDING or FOLLOWING.
         * </pre>
         *
         * <code>optional sint64 n = 2;</code>
         * @return Whether the n field is set.
         */
        @java.lang.Override
        public boolean hasN() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <pre>
         * Can be PRECEDING or FOLLOWING.
         * </pre>
         *
         * <code>optional sint64 n = 2;</code>
         * @return The n.
         */
        @java.lang.Override
        public long getN() {
          return n_;
        }
        /**
         * <pre>
         * Can be PRECEDING or FOLLOWING.
         * </pre>
         *
         * <code>optional sint64 n = 2;</code>
         * @param value The n to set.
         * @return This builder for chaining.
         */
        public Builder setN(long value) {
          bitField0_ |= 0x00000002;
          n_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Can be PRECEDING or FOLLOWING.
         * </pre>
         *
         * <code>optional sint64 n = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearN() {
          bitField0_ = (bitField0_ & ~0x00000002);
          n_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:PartitionWindow.Point)
      }

      // @@protoc_insertion_point(class_scope:PartitionWindow.Point)
      private static final PartitionWindowOuterClass.PartitionWindow.Point DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new PartitionWindowOuterClass.PartitionWindow.Point();
      }

      public static PartitionWindowOuterClass.PartitionWindow.Point getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Point>
          PARSER = new com.google.protobuf.AbstractParser<Point>() {
        @java.lang.Override
        public Point parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Point(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Point> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Point> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public PartitionWindowOuterClass.PartitionWindow.Point getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int START_FIELD_NUMBER = 1;
    private PartitionWindowOuterClass.PartitionWindow.Point start_;
    /**
     * <code>optional .PartitionWindow.Point start = 1;</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .PartitionWindow.Point start = 1;</code>
     * @return The start.
     */
    @java.lang.Override
    public PartitionWindowOuterClass.PartitionWindow.Point getStart() {
      return start_ == null ? PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : start_;
    }
    /**
     * <code>optional .PartitionWindow.Point start = 1;</code>
     */
    @java.lang.Override
    public PartitionWindowOuterClass.PartitionWindow.PointOrBuilder getStartOrBuilder() {
      return start_ == null ? PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : start_;
    }

    public static final int END_FIELD_NUMBER = 2;
    private PartitionWindowOuterClass.PartitionWindow.Point end_;
    /**
     * <code>optional .PartitionWindow.Point end = 2;</code>
     * @return Whether the end field is set.
     */
    @java.lang.Override
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .PartitionWindow.Point end = 2;</code>
     * @return The end.
     */
    @java.lang.Override
    public PartitionWindowOuterClass.PartitionWindow.Point getEnd() {
      return end_ == null ? PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : end_;
    }
    /**
     * <code>optional .PartitionWindow.Point end = 2;</code>
     */
    @java.lang.Override
    public PartitionWindowOuterClass.PartitionWindow.PointOrBuilder getEndOrBuilder() {
      return end_ == null ? PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : end_;
    }

    public static final int WINDOW_TYPE_FIELD_NUMBER = 3;
    private int windowType_;
    /**
     * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
     * @return Whether the windowType field is set.
     */
    @java.lang.Override public boolean hasWindowType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
     * @return The windowType.
     */
    @java.lang.Override public PartitionWindowOuterClass.PartitionWindow.WindowType getWindowType() {
      @SuppressWarnings("deprecation")
      PartitionWindowOuterClass.PartitionWindow.WindowType result = PartitionWindowOuterClass.PartitionWindow.WindowType.valueOf(windowType_);
      return result == null ? PartitionWindowOuterClass.PartitionWindow.WindowType.RANGE : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getStart());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getEnd());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, windowType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStart());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEnd());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, windowType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PartitionWindowOuterClass.PartitionWindow)) {
        return super.equals(obj);
      }
      PartitionWindowOuterClass.PartitionWindow other = (PartitionWindowOuterClass.PartitionWindow) obj;

      if (hasStart() != other.hasStart()) return false;
      if (hasStart()) {
        if (!getStart()
            .equals(other.getStart())) return false;
      }
      if (hasEnd() != other.hasEnd()) return false;
      if (hasEnd()) {
        if (!getEnd()
            .equals(other.getEnd())) return false;
      }
      if (hasWindowType() != other.hasWindowType()) return false;
      if (hasWindowType()) {
        if (windowType_ != other.windowType_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (hasEnd()) {
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + getEnd().hashCode();
      }
      if (hasWindowType()) {
        hash = (37 * hash) + WINDOW_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + windowType_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PartitionWindowOuterClass.PartitionWindow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PartitionWindowOuterClass.PartitionWindow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PartitionWindow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PartitionWindow)
        PartitionWindowOuterClass.PartitionWindowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PartitionWindowOuterClass.internal_static_PartitionWindow_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PartitionWindowOuterClass.internal_static_PartitionWindow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PartitionWindowOuterClass.PartitionWindow.class, PartitionWindowOuterClass.PartitionWindow.Builder.class);
      }

      // Construct using PartitionWindowOuterClass.PartitionWindow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStartFieldBuilder();
          getEndFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (startBuilder_ == null) {
          start_ = null;
        } else {
          startBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (endBuilder_ == null) {
          end_ = null;
        } else {
          endBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        windowType_ = 1;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PartitionWindowOuterClass.internal_static_PartitionWindow_descriptor;
      }

      @java.lang.Override
      public PartitionWindowOuterClass.PartitionWindow getDefaultInstanceForType() {
        return PartitionWindowOuterClass.PartitionWindow.getDefaultInstance();
      }

      @java.lang.Override
      public PartitionWindowOuterClass.PartitionWindow build() {
        PartitionWindowOuterClass.PartitionWindow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PartitionWindowOuterClass.PartitionWindow buildPartial() {
        PartitionWindowOuterClass.PartitionWindow result = new PartitionWindowOuterClass.PartitionWindow(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          if (startBuilder_ == null) {
            result.start_ = start_;
          } else {
            result.start_ = startBuilder_.build();
          }
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (endBuilder_ == null) {
            result.end_ = end_;
          } else {
            result.end_ = endBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.windowType_ = windowType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PartitionWindowOuterClass.PartitionWindow) {
          return mergeFrom((PartitionWindowOuterClass.PartitionWindow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PartitionWindowOuterClass.PartitionWindow other) {
        if (other == PartitionWindowOuterClass.PartitionWindow.getDefaultInstance()) return this;
        if (other.hasStart()) {
          mergeStart(other.getStart());
        }
        if (other.hasEnd()) {
          mergeEnd(other.getEnd());
        }
        if (other.hasWindowType()) {
          setWindowType(other.getWindowType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PartitionWindowOuterClass.PartitionWindow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PartitionWindowOuterClass.PartitionWindow) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private PartitionWindowOuterClass.PartitionWindow.Point start_;
      private com.google.protobuf.SingleFieldBuilderV3<
          PartitionWindowOuterClass.PartitionWindow.Point, PartitionWindowOuterClass.PartitionWindow.Point.Builder, PartitionWindowOuterClass.PartitionWindow.PointOrBuilder> startBuilder_;
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       * @return Whether the start field is set.
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       * @return The start.
       */
      public PartitionWindowOuterClass.PartitionWindow.Point getStart() {
        if (startBuilder_ == null) {
          return start_ == null ? PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : start_;
        } else {
          return startBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       */
      public Builder setStart(PartitionWindowOuterClass.PartitionWindow.Point value) {
        if (startBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          start_ = value;
          onChanged();
        } else {
          startBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       */
      public Builder setStart(
          PartitionWindowOuterClass.PartitionWindow.Point.Builder builderForValue) {
        if (startBuilder_ == null) {
          start_ = builderForValue.build();
          onChanged();
        } else {
          startBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       */
      public Builder mergeStart(PartitionWindowOuterClass.PartitionWindow.Point value) {
        if (startBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
              start_ != null &&
              start_ != PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance()) {
            start_ =
              PartitionWindowOuterClass.PartitionWindow.Point.newBuilder(start_).mergeFrom(value).buildPartial();
          } else {
            start_ = value;
          }
          onChanged();
        } else {
          startBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       */
      public Builder clearStart() {
        if (startBuilder_ == null) {
          start_ = null;
          onChanged();
        } else {
          startBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       */
      public PartitionWindowOuterClass.PartitionWindow.Point.Builder getStartBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStartFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       */
      public PartitionWindowOuterClass.PartitionWindow.PointOrBuilder getStartOrBuilder() {
        if (startBuilder_ != null) {
          return startBuilder_.getMessageOrBuilder();
        } else {
          return start_ == null ?
              PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : start_;
        }
      }
      /**
       * <code>optional .PartitionWindow.Point start = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PartitionWindowOuterClass.PartitionWindow.Point, PartitionWindowOuterClass.PartitionWindow.Point.Builder, PartitionWindowOuterClass.PartitionWindow.PointOrBuilder> 
          getStartFieldBuilder() {
        if (startBuilder_ == null) {
          startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PartitionWindowOuterClass.PartitionWindow.Point, PartitionWindowOuterClass.PartitionWindow.Point.Builder, PartitionWindowOuterClass.PartitionWindow.PointOrBuilder>(
                  getStart(),
                  getParentForChildren(),
                  isClean());
          start_ = null;
        }
        return startBuilder_;
      }

      private PartitionWindowOuterClass.PartitionWindow.Point end_;
      private com.google.protobuf.SingleFieldBuilderV3<
          PartitionWindowOuterClass.PartitionWindow.Point, PartitionWindowOuterClass.PartitionWindow.Point.Builder, PartitionWindowOuterClass.PartitionWindow.PointOrBuilder> endBuilder_;
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       * @return Whether the end field is set.
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       * @return The end.
       */
      public PartitionWindowOuterClass.PartitionWindow.Point getEnd() {
        if (endBuilder_ == null) {
          return end_ == null ? PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : end_;
        } else {
          return endBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       */
      public Builder setEnd(PartitionWindowOuterClass.PartitionWindow.Point value) {
        if (endBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          end_ = value;
          onChanged();
        } else {
          endBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       */
      public Builder setEnd(
          PartitionWindowOuterClass.PartitionWindow.Point.Builder builderForValue) {
        if (endBuilder_ == null) {
          end_ = builderForValue.build();
          onChanged();
        } else {
          endBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       */
      public Builder mergeEnd(PartitionWindowOuterClass.PartitionWindow.Point value) {
        if (endBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              end_ != null &&
              end_ != PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance()) {
            end_ =
              PartitionWindowOuterClass.PartitionWindow.Point.newBuilder(end_).mergeFrom(value).buildPartial();
          } else {
            end_ = value;
          }
          onChanged();
        } else {
          endBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       */
      public Builder clearEnd() {
        if (endBuilder_ == null) {
          end_ = null;
          onChanged();
        } else {
          endBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       */
      public PartitionWindowOuterClass.PartitionWindow.Point.Builder getEndBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getEndFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       */
      public PartitionWindowOuterClass.PartitionWindow.PointOrBuilder getEndOrBuilder() {
        if (endBuilder_ != null) {
          return endBuilder_.getMessageOrBuilder();
        } else {
          return end_ == null ?
              PartitionWindowOuterClass.PartitionWindow.Point.getDefaultInstance() : end_;
        }
      }
      /**
       * <code>optional .PartitionWindow.Point end = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          PartitionWindowOuterClass.PartitionWindow.Point, PartitionWindowOuterClass.PartitionWindow.Point.Builder, PartitionWindowOuterClass.PartitionWindow.PointOrBuilder> 
          getEndFieldBuilder() {
        if (endBuilder_ == null) {
          endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              PartitionWindowOuterClass.PartitionWindow.Point, PartitionWindowOuterClass.PartitionWindow.Point.Builder, PartitionWindowOuterClass.PartitionWindow.PointOrBuilder>(
                  getEnd(),
                  getParentForChildren(),
                  isClean());
          end_ = null;
        }
        return endBuilder_;
      }

      private int windowType_ = 1;
      /**
       * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
       * @return Whether the windowType field is set.
       */
      @java.lang.Override public boolean hasWindowType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
       * @return The windowType.
       */
      @java.lang.Override
      public PartitionWindowOuterClass.PartitionWindow.WindowType getWindowType() {
        @SuppressWarnings("deprecation")
        PartitionWindowOuterClass.PartitionWindow.WindowType result = PartitionWindowOuterClass.PartitionWindow.WindowType.valueOf(windowType_);
        return result == null ? PartitionWindowOuterClass.PartitionWindow.WindowType.RANGE : result;
      }
      /**
       * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
       * @param value The windowType to set.
       * @return This builder for chaining.
       */
      public Builder setWindowType(PartitionWindowOuterClass.PartitionWindow.WindowType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        windowType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .PartitionWindow.WindowType window_type = 3 [default = RANGE];</code>
       * @return This builder for chaining.
       */
      public Builder clearWindowType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        windowType_ = 1;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PartitionWindow)
    }

    // @@protoc_insertion_point(class_scope:PartitionWindow)
    private static final PartitionWindowOuterClass.PartitionWindow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PartitionWindowOuterClass.PartitionWindow();
    }

    public static PartitionWindowOuterClass.PartitionWindow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PartitionWindow>
        PARSER = new com.google.protobuf.AbstractParser<PartitionWindow>() {
      @java.lang.Override
      public PartitionWindow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PartitionWindow(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PartitionWindow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PartitionWindow> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PartitionWindowOuterClass.PartitionWindow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PartitionWindow_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PartitionWindow_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PartitionWindow_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PartitionWindow_Point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026partition_window.proto\"\344\002\n\017PartitionWi" +
      "ndow\022%\n\005start\030\001 \001(\0132\026.PartitionWindow.Po" +
      "int\022#\n\003end\030\002 \001(\0132\026.PartitionWindow.Point" +
      "\0227\n\013window_type\030\003 \001(\0162\033.PartitionWindow." +
      "WindowType:\005RANGE\032<\n\005Point\022(\n\004type\030\001 \001(\016" +
      "2\032.PartitionWindow.PointType\022\t\n\001n\030\002 \001(\022\"" +
      "l\n\tPointType\022\027\n\023UNBOUNDED_PRECEDING\020\001\022\r\n" +
      "\tPRECEDING\020\002\022\027\n\023UNBOUNDED_FOLLOWING\020\003\022\r\n" +
      "\tFOLLOWING\020\004\022\017\n\013CURRENT_ROW\020\005\" \n\nWindowT" +
      "ype\022\t\n\005RANGE\020\001\022\007\n\003ROW\020\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PartitionWindow_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PartitionWindow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PartitionWindow_descriptor,
        new java.lang.String[] { "Start", "End", "WindowType", });
    internal_static_PartitionWindow_Point_descriptor =
      internal_static_PartitionWindow_descriptor.getNestedTypes().get(0);
    internal_static_PartitionWindow_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PartitionWindow_Point_descriptor,
        new java.lang.String[] { "Type", "N", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
